-- Drop existing tables (if any)
DROP TABLE IF EXISTS trips;
DROP TABLE IF EXISTS country_rules;

-- Create users table handled natively by Supabase Auth (auth.users), 
-- but a public mapping can be useful:
CREATE TABLE IF NOT EXISTS profiles (
  id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
  email text,
  nationality text
);

-- Note: In this MVP the backend uses mock data. When moving to Supabase, 
-- you will use this schema.

-- Trips table
CREATE TABLE trips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users,
  iso_code varchar(2) NOT NULL,
  entry_date DATE NOT NULL,
  exit_date DATE,
  is_schengen BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Country Rules (Static Limits)
CREATE TABLE country_rules (
  iso_code varchar(2) PRIMARY KEY,
  tourist_limit_days INT DEFAULT 90,
  tax_limit_days INT DEFAULT 183
);

-- Insert dummy rules
INSERT INTO country_rules (iso_code, tourist_limit_days, tax_limit_days) VALUES
('ES', 90, 183),
('IT', 90, 183),
('TH', 60, 180),
('PT', 90, 183);
